version: "3"

services:
    db:
        image: mysql
        container_name: laravel_db
        ports:
            - 33067:3306
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: ./docker/php/php.dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        ports:
            - 8008:80
        volumes:
            - .:/var/www/html
            - ./docker/php/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    cron:
        build:
            context: .
            dockerfile: ./docker/cron/cron.dockerfile
        container_name: laravel_cron
        volumes:
            - .:/var/www/html

    horizon:
        build:
            context: .
            dockerfile: ./docker/horizon/horizon.dockerfile
        container_name: laravel_horizon
        volumes:
            - .:/var/www/html

    redis:
        image: redis
        container_name: laravel_redis
        ports:
            - "63791:6379"
